name: build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
env:
  sdl_version: "2.0.14"   



jobs:
    
  win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
            
      - name: get SDL2
        run: |
          curl https://www.libsdl.org/release/SDL2-devel-${{ env.sdl_version }}-VC.zip -o SDL2.zip
          7z x SDL2.zip

      - name: get FNA3D
        run: git clone --recursive https://github.com/andreakarasho/FNA3D
          
      - name: build FNA3D STATIC
        run: |
          cd FNA3D
          mkdir build_static
          cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=ON -DSDL2_INCLUDE_DIRS="${{ github.workspace }}\SDL2-${{ env.sdl_version }}\include" -DSDL2_LIBRARIES="${{ github.workspace }}\SDL2-${{ env.sdl_version }}\lib\x64\SDL2.lib;${{ github.workspace }}\SDL2-${{ env.sdl_version }}\lib\x64\SDL2main.lib" -B build_static 
          cmake --build build_static/ --config Release
          
      - name: build FNA3D SHARED
        run: |
          cd FNA3D
          mkdir build_shared
          cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=OFF -DSDL2_INCLUDE_DIRS="${{ github.workspace }}\SDL2-${{ env.sdl_version }}\include" -DSDL2_LIBRARIES="${{ github.workspace }}\SDL2-${{ env.sdl_version }}\lib\x64\SDL2.lib;${{ github.workspace }}\SDL2-${{ env.sdl_version }}\lib\x64\SDL2main.lib" -B build_shared 
          cmake --build build_shared/ --config Release
          
      - name: Create package
        run: 7z a win-x64-release.zip ./FNA3D/build_shared/FNA3D.dll ./FNA3D/build_static/FNA3D.lib
          
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: win-x64-release.zip
          asset_name: win-x64-release.zip
          tag: ${{ github.ref }}
          overwrite: true


  linux-x64:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     
     - name: get SDL2
       run: |
         git clone --recursive https://github.com/libsdl-org/SDL.git
         cd SDL
         mkdir build
         cd build
         ../configure
         make
         sudo make install
     
     - name: get FNA3D
       run: git clone --recursive https://github.com/andreakarasho/FNA3D
     
     - name: build FNA3D STATIC
       run: |
         cd FNA3D
         mkdir build_static
         cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=ON -B build_static
         cmake --build build_static/ --config Release
         
     - name: build FNA3D SHARED
       run: |
         cd FNA3D
         mkdir build_shared
         cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=OFF -B build_shared
         cmake --build build_shared/ --config Release
         
     - name: Create package
       run: zip linux-x64-release.zip ./FNA3D/build_shared/libFNA3D.so ./FNA3D/build_static/libFNA3D.a
          
     - name: Upload
       uses: svenstaro/upload-release-action@v2
       with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: linux-x64-release.zip
         asset_name: linux-x64-release.zip
         tag: ${{ github.ref }}
         overwrite: true


  macOS:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2
     
     - name: get SDL2
       run: |
         git clone --recursive https://github.com/libsdl-org/SDL.git
         cd SDL
         mkdir build
         cd build
         ../configure
         make
         sudo make install
     
     - name: get FNA3D
       run: git clone --recursive https://github.com/andreakarasho/FNA3D
     
     - name: build FNA3D STATIC
       run: |
         cd FNA3D
         mkdir build_static
         cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=ON -B build_static
         cmake --build build_static/ --config Release
         
     - name: build FNA3D SHARED
       run: |
         cd FNA3D
         mkdir build_shared
         cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=OFF -B build_shared
         cmake --build build_shared/ --config Release
         
     - name: Create package
       run: zip osx-x64-release.zip ./FNA3D/build_shared/libFNA3D.dylib ./FNA3D/build_static/libFNA3D.a
          
     - name: Upload
       uses: svenstaro/upload-release-action@v2
       with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: osx-x64-release.zip
         asset_name: osx-x64-release.zip
         tag: ${{ github.ref }}
         overwrite: true
