name: build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:

  win-x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: get SDL2
        run: curl https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip -o SDL2

      - name: Get FNA3D
        run: git clone --recursive https://github.com/andreakarasho/FNA3D
          
      - name: build FNA3D STATIC
        run: |
          cd FNA3D
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=ON -B build
          cmake --build build/ --config Release
          
      - name: build FNA3D SHARED
        run: |
          cd FNA3D
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -DFNA3D_STATIC=OFF -B build
          cmake --build build/ --config Release


